version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  topics:
    image: confluentinc/cp-kafka
    depends_on:
      - kafka
    command: sh -c "echo 'Waiting for Kafka to be available...'; while ! nc -z kafka 9092; do sleep 1; done; sleep 5; topics --create --topic topic1 --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092; topics --create --topic topic2 --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092; echo 'Topics created!'; sleep infinity"
